spring.datasource.url: jdbc:h2:file:./camunda-h2-database
PassportLenght: 10
urlClientByPassport: http://192.168.1.161:8086/clients/passports/

host: 192.168.1.161:8086
urlPathClientByPassport: /clients/passports/
urlPathClientRegistration: /clients/


camunda.bpm.admin-user:
  id: demo
  password: demo